### ISSUE TITLE
Backend Slack Chat

### ISSUE THREAD

**Issue by sven15** [Integreat/cms#185]
Verwalter die Möglichkeit geben, sich untereinander auszutauschen.

**Comment by Dalanie** [comment]
Sehr gute Wahl. Ich bin jedes Wochenende mit nen Haufen Slack-Mitarbeitern unterwegs! Ich frag mal nach zwecks kostenfreier Business-Version

**Comment by Meash** [comment]
Ist das integrierbar in WordPress?

**Comment by dkehne** [comment]
@pblanz kannst du das mal prüfen? :)

**Comment by Meash** [comment]
Moment, was wollen wir hier eigentlich? Einen Chat in WordPress für uns / für Verwalter? Das sollten wir vorher noch zusammenschreiben, was genau wir uns vorstellen.

**Comment by sven15** [comment]
resolved for now with https://hilfe.integreat-app.de/qa/

**Comment by mschrimpf** [comment]
An actual chat functionality is still very much desired by our users. A forum-like function is already realized at the site mentioned by @sven15 but not used as much (possibly because it is at another site).
There are a couple of plugins that enable a chat within one instance but I did not found any that support chats across instances.
Ideally, such a functionality is embedded within the standard UI, e.g. a chat at the bottom right.

**Comment by sven15** [comment]
we could also do some research about integrating q2a into the WP backend.

**Comment by mschrimpf** [comment]
duplicate of #398
