### ISSUE TITLE
CDN aufsetzen

### ISSUE THREAD

**Issue by Meash** [Integreat/cms#234]
Wir skalieren sehr stark, die Technik sollte mitmachen.
Schlage vor, mit CDN anzufangen und dann Caching dazuzuschalten.

Konkret die Servertypen:
1. **CDN**: verteilt Requests - kein Caching
2. **Edit**: Eingabe durch Kommunen und Organisationen - müssen uns noch anschauen, was hier gecached werden kann, da alle Seiten dynamisch aus der Datenbank gebaut werden
3. **API**: Read-Only Server, der alle API Anfragen beantwortet - Caching für z.B. 30 Minuten zusammen mit extrem hoher Nebenläufigkeit durch keine Updates sollte reichen

Updates müssen dann auf alle Server gepushed werden. Idealerweise werden auf den Server, der gerade upgedated wird, keine Requests verteilt. Der sollte erst wieder live gehen, nachdem die Test Suite durchgelaufen ist.

**Comment by Meash** [comment]
Interessante WP Caching Plugins: [WP Super Cache](https://wordpress.org/plugins/wp-super-cache/), [WP Fastest Cache](https://wordpress.org/plugins/wp-fastest-cache/)

**Comment by dkehne** [comment]
Wer kann das umsetzen? @pblanz @sven15 ?

**Comment by Meash** [comment]
Wir warten noch auf die Rückmeldung von @MaximilianSchreieck, ob das LRZ uns nicht bereits etwas AWS-ähnliches bieten kann.

**Comment by sven15** [comment]
vmkrcmar21 ist jetzt MySQL Master, vmkrcmar79 MySQL Slave. vmkrcmar81 fungiert apache2 mit mod_proxy als load balancer. vmkrcmar21 erledigt read only tasks (front end) und vmkrcmar21 read-write (back end). Apache2+PHP läuft zunächst auf 21 und 79 weiter, kann aber von den Datenbankservern ausgelagert werden.

**Comment by Meash** [comment]
Wie synchronisieren wir die Datenbanken?

**Comment by sven15** [comment]
synchronisieren sich automatisch, mysql master slave system. schon eingerichtet.

**Comment by Meash** [comment]
Cool!

**Comment by sven15** [comment]
Im Endeffekt terminieren alle HTTP und HTTPS Verbindungen dann auf vmkrcmar81, welcher mittels mod_proxy die Anfragen auf die PHP-Server verteilt. Da muss ich jetzt noch frickeln, da mod_rewrite auf dem vmkrcmar21 zu Problemen führt. Das bekommt man aber sicher geregelt.

**Comment by sven15** [comment]
Configuration Example is available in https://github.com/Integreat/cms/wiki/Load-Balancing-configuration
Needs to be implemented for live system.

**Comment by sven15** [comment]
I forwarded a mod_substitute / mod_sed problem to the Apache2 Users ML:
http://mail-archives.apache.org/mod_mbox/httpd-users/201603.mbox/browser

**Comment by sven15** [comment]
As long as a user is only using one site, it should be working now: https://cms.integreat-app.de/somecity/wp-admin/
There is also a foward of http://somecity.integreat-app.de/ to the previous URL. It's possible to test this by adding "131.159.56.12 somecity.integreat-app.de" to your hosts file.

**Comment by Meash** [comment]
I don't think we can assume that a user is only on one site. For instance,
I am not.

**Comment by sven15** [comment]
Yes, you're right. However those are mostly admin users like us who know what to do. The issue is, that without a specific site you'll get a 302 Found Result and links in those are not replaced. However we could at some point add redirects into vmkrcmar21 that all requests from outside will be redirected to https://cms.integreat-app.de/. Im also still looking into the issue of using mod_substitute on other results than 200 OK.

**Comment by Meash** [comment]
Why exactly can two sites not be open at the same time? I'm not a friend of
these special cases, they usually indicate a problem.

**Comment by sven15** [comment]
Cookies are set for a specific URL. If you login on https://cms.integreat-app.de/wp-admin/ and your user is only valid for https://cms.integreat-app.de/somecity/wp-admin/ you will be forwarded to https://cms.integreat-app.de/wp-admin/edit.php with HTTP/1.1 403 Forbidden and a link to the Dashboard of somecity. However mod_subistute is only working on 403 pages, therefore it will not substitute the FQDN of the backend server with cms.integreat-app.de. You can uses the link directly to the backend server, but then you will have to login again and without HTTPS.

I think we could tell Wordpress to replace 403 Forbidden with 200 OK codes, because this will have no impact on the functionality. I'm going to try this on our wordpress_test.

**Comment by sven15** [comment]
Yes, adding the following will fix the problem:
    function change_403_codes() {
        if(http_response_code () == 403) {
                http_response_code(200);
        }
    }
    add_action ('shutdown','change_403_codes');

**Comment by sven15** [comment]
Final tasks for go live:

- merge branch remove-403
- replace domains in live system (vmkrcmar21.informatik.tu-muenchen.de to cms.integreat-app.de)
- change mod_headers RequestHeader edit on vmkrcmar21

**Comment by sven15** [comment]
The 403 fix is for unknown reasons not working on wordpress_test.

**Comment by sven15** [comment]
Done. \o/
Results can be seen on https://cms-test.integreat-app.de/
