### ISSUE TITLE
Delete landing page and redirect

### ISSUE THREAD

**Issue by mschrimpf** [Integreat/cms#283]
The concents of the root site `http://vmkrcmar21.informatik.tu-muenchen.de/wordpress/` should be deleted (posts, plugins, themes) and redirect to `http://integreat-app.de`

Note that the plugins and themes should be deleted in a pull request (probably along with the redirect implementation) while the contents of the site have to be modified in production.

**Comment by sascha11110** [comment]
At the moment it is not a good idea to delete the whole landing page because the redirects that I set up are handled by (instanced-based) plugin "Redirection". So if your want to delete the landingpage and all its posts, plugins and themes as mentioned by @Meash we need to find a better solution.

I set up redirects for all links if could find via "site:http://vmkrcmar21.informatik.tu-muenchen.de/wordpress/" that are related with the old landing page.

**Comment by Meash** [comment]
Would it work if we don't delete the redirect plug-in though? We need some
sort of redirection anyways.

**Comment by sascha11110** [comment]
The plugin cannot be used in network admin and must be placed in the "correct" instance. So, once the instance is deleted, it will not work any longer.

But I think it is not too difficult to create an own plugin for this purpose that uses wp_redirect() function.

**Comment by Meash** [comment]
We can't delete the instance AFAIK since it is the root instance. So having
a redirect plug-in only for that particular instance is perfectly fine.

**Comment by sven15** [comment]
@sascha11110 can you do this?

**Comment by sascha11110** [comment]
Now all live instances are listed via the root instance. The plugin that redirects old links to the new landing page (integreat-app.de) is still activated.
