### ISSUE TITLE
Automatically activate themes

### ISSUE THREAD

**Issue by mschrimpf** [Integreat/cms#351]
Based on #345, themes should automatically be activated so that we do not have to do it manually.

**Comment by sascha11110** [comment]
Is this really necessary? If we create a new instance (blog) the "right" theme is activated by duplicating our default instance. I think it is not so much work to activate the new theme (#345) in all existing instances manually.

In the future the theme will by overwritten by new versions so there is no need of activating themes.

**Comment by Meash** [comment]
The two main arguments are:
1. there is the fairly simply wp-cli command `wp activate theme <theme name>` ([we do the same for plugins](https://github.com/Integreat/cms/blob/2efbed4a2b9620c56bf1499e8ae574cd3f65f196/wp-activate-plugins.sh))
2. everyone would have to update the local installation for the new theme. From experience, this involves lots of explaining. A script saves us from human errors at least

I will stop working on it if it turns out to be too much work but I think it would make sense.

**Comment by sascha11110** [comment]
Okay, agree. Especially the second argument is convincing

**Comment by sven15** [comment]
not necessary. setting is copied from template blog. And there is no cli option for multisites.
