### ISSUE TITLE
Events GUI simplification

### ISSUE THREAD

**Issue by svenseeberg** [Integreat/cms#406]
Hide everything except title, description, location and time/date. Input is always translated automatically.

**Comment by sven15** [comment]
Advanced Custom Fields Pro (#405)

**Comment by FritjofK** [comment]
Not worth the time

**Comment by sven15** [comment]
From #485

To simplify the event creation process we should remove the "Sprache"-Widget where you can manage the Translations from the event detail page. We should rather enable the auto-translation for EVERY event which is saved. Save-Button = Auto-Translation is created.

This topic occured because we currently build the cms documentation and there is nothing to explain regarding the Sprachen-Widget for Events because it's a waste of time to insert translations manually and duplication should be avoided directly if auto-translation is a simple way.

**Comment by sven15** [comment]
Open: Autotranslate

**Comment by sven15** [comment]
On save create hook that translates post and required post meta

**Comment by svenseeberg** [comment]
We need to discuss at I8K whether changes affect #533

**Comment by svenseeberg** [comment]
Events Manager plugin did that itself.
