### ISSUE TITLE
Persian/Arabic Texts from "right to left" after Auto-Translation and after Bullet-Points

### ISSUE THREAD

**Issue by dkehne** [Integreat/cms#438]
After clicking the auto translation-button texts in arabic and persian language are displayed incorrectly. They are from "left to right" instead of "right to left". Currently one has to change it manually for every page.

**Comment by sven15** [comment]
Concerned languages must be hardcoded in auto translation plugin and a dir="rtl" must be added to all <p> tags

**Comment by FritjofK** [comment]
Maybe it is a connected topic. 
When Bulltet Points are used it is written from left to right while the remainder of the text stays from right to left.

**Comment by sven15** [comment]
This is very problematic. @mschrimpf: does the autotranslation plugin send the full HTML to bing or string by string?

**Comment by sven15** [comment]
I think there is easy solution for this. Best way would be manually formatting the translated pages. I know that this sucks but other solutions won't work well.

**Comment by mschrimpf** [comment]
@sven15 I think we send full HTML, i.e. the full page content. Can't we just automatically adjust formatting for these languages? Our manual is gonna be a whole book if we don't automate some things (even though it might not be top priority).

**Comment by sven15** [comment]
Only good solution is to mark everything in editor and use Right To Left button (at least twice)

**Comment by sven15** [comment]
Reopened due to wishes in #486

To simplify the event creation process we should remove the "Sprache"-Widget where you can manage the Translations from the event detail page. We should rather enable the auto-translation for EVERY event which is saved. Save-Button = Auto-Translation is created.

This topic occured because we currently build the cms documentation and there is nothing to explain regarding the Sprachen-Widget for Events because it's a waste of time to insert translations manually and duplication should be avoided directly if auto-translation is a simple way.
