### ISSUE TITLE
Remove/Undisplay "Sprache"-Widget from Events

### ISSUE THREAD

**Issue by dkehne** [Integreat/cms#485]
To simplify the event creation process we should remove the "Sprache"-Widget where you can manage the Translations from the event detail page. We should rather enable the auto-translation for EVERY event which is saved. Save-Button = Auto-Translation is created.

This topic occured because we currently build the cms documentation and there is nothing to explain regarding the Sprachen-Widget for Events because it's a waste of time to insert translations manually and duplication should be avoided directly if auto-translation is a simple way.

**Comment by sven15** [comment]
reopened #438 and added this.

**Comment by sven15** [comment]
To simplify the event creation process we should remove the "Sprache"-Widget where you can manage the Translations from the event detail page. We should rather enable the auto-translation for EVERY event which is saved. Save-Button = Auto-Translation is created.

This topic occured because we currently build the cms documentation and there is nothing to explain regarding the Sprachen-Widget for Events because it's a waste of time to insert translations manually and duplication should be avoided directly if auto-translation is a simple way.

**Comment by sven15** [comment]
Confused some browser tabs

**Comment by sven15** [comment]
duplicate of #406
