### ISSUE TITLE
Linking to extras from pages

### ISSUE THREAD

**Issue by benginoe** [Integreat/cms#595]
Cities want to link from pages to a extra function. (Keep in mind, what happens if the exta is not anymore available)

**Comment by svenseeberg** [comment]
@maxammann / @thimmy687 can you please provide input what kind of information you would need from the backend to implement this in the apps?

**Comment by maxammann** [comment]
@svenseeberg So we need the whole permalink instead of just the id of the linked post. Also it would be good to know in which format the permalink comes. If it contains the location, language, starts with http://.. etc.

**Comment by svenseeberg** [comment]
Are we talking about the same thing here? I think this issue is about the extras that can be enabled for each site. See https://github.com/Integreat/cms/wiki/REST-API#5-ig-extras

**Comment by timoludwig** [comment]
As we deliver all relevant information about the extras in the APIv3, can we just insert a placeholder here, like `<span class="ig-extra ig-serlo-abc"></span>"` (where `serlo-abc` could be just another alias of an extra)? The Apps could then fetch the current URL of the extra through the API and we don't run into problems if links in the page-content are outdated.

**Comment by svenseeberg** [comment]
@maxammann @Schedulaar @klinzo @thimmy687 can you work with a span that has a defined class?

**Comment by maxammann** [comment]
It's a bit hacky imo but should work for the webapp. I'd propose a `<ig-extra>serlo-abc</ig-extra>` though.

**Comment by timoludwig** [comment]
Ok. Do you have a better idea how we could implement this in a proper way?
Of course we could replace the placeholder with the correct url in our API, but this may slow down the pages endpoint and I don't know how to handle the Sprungbrett-link, which is just an API.

**Comment by maxammann** [comment]
I think it would be cool if the api would deliver some specified template instead of html.
This issue is very much linked to https://integreat.atlassian.net/browse/WEBAPP-211.

In the webapp we dont want any plain-old `<a>` tags. Also in this case we dont want the `<ig-extra>`. We want to replace them with a react counter part.

In order to achive this we need to 'parse' the static html internally and transform it so it no longer does a HTTP GET for example when clicking on an anchor tag.

We will discuss this on the co-working days this week.


For the react folks: http://wix.github.io/react-templates/
One idea would be that the endpoint delivers a react component instead of a html string :)

**Comment by svenseeberg** [comment]
@maxammann did you come up with an idea?

**Comment by svenseeberg** [comment]
No changes to backend required.

**Comment by maxammann** [comment]
Done in https://issues.integreat-app.de/browse/WEBAPP-347
