### ISSUE TITLE
Recurring events

### ISSUE THREAD

**Issue by benginoe** [Integreat/cms#596]
Recurring events are requested from multiple cities as absolut necessary functionality.

Changes needed on API and frontend.

**Comment by svenseeberg** [comment]
@timoludwig sorry that this ticket was not concise enough. Your PR would be a solution to the problem if we implemented repeating events in our frontends / apps.
We had discussions on the I9K but did not care to update this ticket with the results. One of the results was, that calculating the repeated events in the backend would be easier to code than doing it in each app.

Update of ticket:
(Recurring events are requested from at least one city as necessary for going live.)

The easiest way to go forward is to fully implement this functionality in the back end of the API. This means that we do not have to write code for the 3 different apps we're currently using. We might then also be able to leverage functions included in the Event Manger plugin to calculate repeating events into items that are displayed.

**Example illustrating the idea (arbitrary dates used)**
1. Admin is creating an event on 2017-10-01 which is scheduled for 2017-10-31 and repeated on the following two weeks.
2. App is downloading the three event items on 2017-10-07, each has it's own ID.
3. Admin is changing the the event (for simplicity lets say only the description)
4. App is contacting the API again on 2017-11-04 with the since=2017-10-07. The backend now has to send updates for only the repeated events.

**Problem**
We need to associate all repeating items delivered via the API with the original database entry. We need to somehow create a deterministic algorithm that produces unique but reproducible IDs for the API repeated event items.
The backend only has the ID for the first entry in it's database. I'm not sure if the current queries even get the old event.
**Solution(???)**
A hash algorithm that produces numbers only. We can then hash values that do not change, like: ID in database, creation date. Additionally, we need to identify or create properties for each repeating event that do not change and can be taken into the hash. With a long enough hash sum we wont get any collisions with ordinary event IDs. @maxammann @thimmy687 would very high ID numbers be a problem for the web or xamarin app?
@all were are the pitfalls with this idea?

**Comment by svenseeberg** [comment]
See PR comment.
