### ISSUE TITLE
Published child category with unpublished parent

### ISSUE THREAD

**Issue by Schedulaar** [Integreat/cms#655]
Currently we (webapp) have a problem with the Lüneburg-instance: We receive a published child category whose parent is not published. Since we need to have a proper parent category attached (for breadcrumbs etc.) and it makes no sense to have children without a parent, the webapp will only show an error message in this case (So the whole instance cannot be shown!). As a solution, it would be good, if, once the user sets a parent entry to unpublished, all its (deep) children will be set to unpublished as well.

**Comment by svenseeberg** [comment]
Sound reasonable.

**Comment by svenseeberg** [comment]
AFAIK we are iterating down the tree with a recurrent function. If a node is not published, we can just end the recursion down to it's leaves.
Basically
```
if($published) $children = get_pages( array( 'child_of' => $post->ID ) );
```

**Comment by timoludwig** [comment]
I see two different approaches to solve this issue:

1. Change the way we collate the pages in the API: Currently, [we use a single WP_Query-object](https://github.com/Integreat/cms/blob/328ebf270e87ee9180280712962b2a445525d4f3/wp-content/plugins/ig-wp-api-extensions/endpoints/v3/APIv3_Posts_Abstract.php#L19-L25) to fetch all pages with one query. Alternatively, we could use a recurrent function to start with the published root-pages and get all published descendants subsequently [(like I did for the mpdf-plugin)](https://github.com/Integreat/cms/blob/328ebf270e87ee9180280712962b2a445525d4f3/wp-content/plugins/ig-mpdf/IntegreatMpdfAPI.php#L68-L85). Thus, the children of unpublished posts won't be in the API result. An advantage of this approach is that we won't need much additional code, as the recurrent function already exists in the ig-mpdf plugin. A drawback is the presumable performance-degradation due to the recurrent function (in my eyes a decisive aspect, but we might have to test this).
2. Whenever a page is set to 'draft', we also apply this to all descendants of the page. This could be done by using a [post-status hook](https://codex.wordpress.org/Post_Status_Transitions). A drawback might be, that the cities' administrators might not notice this process and get confused once they re-publish the unpublished parent page, because all of the children are unpublished as well, unless they are published manually. Also, we should probably include a functionality to prevent child-pages of unpublished pages to be published manually.

What do you think is the most suitable solution?

**Comment by svenseeberg** [comment]
I think we need to go with the API-only variant. Because if we set all children to draft once, we would have to store a post-meta for each child whether we can publish it again, as soon as the parent gets published. Also, this method is not compatible with the current state of the database.

**Comment by svenseeberg** [comment]
We can use the following function: https://developer.wordpress.org/reference/functions/get_post_ancestors/ and add the following (extremely inefficient) function to our API:
```
ig_api_check_published_parent($post_id) {
    $ancestors = get_post_ancestors($post_id);
    for($ancestors as $ancestor) {
       if('publish' != get_post_status($ancestor))
           return false;
    }
    return true;
}
```

However, it would be better to create the tree structure once and keep it in the memory for the whole API call.

**Comment by svenseeberg** [comment]
Even better: https://github.com/Integreat/cms/blob/328ebf270e87ee9180280712962b2a445525d4f3/wp-content/plugins/ig-mpdf/IntegreatMpdfAPI.php#L68-L85

This fucntion returns a list of all published pages, if called with parameter $id=0. During the API call we just need to check if a page ID exists in this return array.
