### ISSUE TITLE
Translate links in content

### ISSUE THREAD

**Issue by timoludwig** [Integreat/cms#670]

**Comment by svenseeberg** [comment]
This is difficult, because this is mainly a problem of the translation process. The links must be changed when being exported to xliff, while being translated or on the import. Alternatively we can replace the link during API delivery. However, this sounds expensive on resources. The problem is, that we don't know when to keep an original link or when to replace. A solution would be an additional link attribute like "keep link".

**Comment by svenseeberg** [comment]
I set the priority to low, because I have no idea how to solve this.

**Comment by svenseeberg** [comment]
An issue for Django was created.
