### ISSUE TITLE
update robots.txt

### ISSUE THREAD

**Issue by benginoe** [Integreat/cms#712]
Please use following robots.txt 

"User-Agent: *
Disallow: /
Allow: /wp-json/"

we need to allow the ressources for crawler

**Comment by svenseeberg** [comment]
If the crawler is crawling the API, does it then send the user to the correct page?

**Comment by benginoe** [comment]
i guess so, its the official error from google ...

**Comment by Schedulaar** [comment]
It's necessary for the crawler that we don't block the API via robots.txt, because otherwise it can't build the pages at web.integreat-app.de (because there we use the API from cms.integreat-app.de client side which is blocked by the robots.txt and the crawler refuses to load it to build the page).
I don't think that Google indexes JSONs at all (and lists them in the search results) - at least i've never  seen any Google search result directing to a json.
Not sure about other SEs, but I think they'll have to adjust to Google's methods in the long run anyway ^^

**Comment by Schedulaar** [comment]
Although we could think about blocking the PDF endpoint 🤔
