### ISSUE TITLE
Not all events are shown on tab "All"

### ISSUE THREAD

**Issue by dkehne** [Integreat/cms#886]
In the cms not all events are shown under tab "all". The number is correct but the events are missing. It seems to be that alle events in draft-state are not shown. If one clicks on "draft" tab it shows the events in draft-modus, under "all"-tab it only shows published events. See attached screenshots
![alle](https://user-images.githubusercontent.com/4182469/49871413-7d510f00-fe16-11e8-95f5-699b66ca150b.PNG)
![entwurf](https://user-images.githubusercontent.com/4182469/49871414-7d510f00-fe16-11e8-8255-14fdd81bb8f7.PNG)

**Comment by timoludwig** [comment]
This issue has nothing to do with the draft-status. Instead, the upper picture shows the "future events" filter instead of "all events". The error occurred because the event "Café Kunterbunt" was created without a start- and end-date. Thus, the placeholder 01.01.1970 is shown which is not in the future. We consider this behaviour a user error and we will not change the wordpress core or events-manager plugin.
This behaviour was added to the following wiki page: [https://wiki.integreat-app.de/veranstaltungen](https://wiki.integreat-app.de/veranstaltungen#einmalige_veranstaltungen).
