### ISSUE TITLE
Replace id with path in the response of a "hash"/"diff" request

### ISSUE THREAD

**Issue by NKlug** [Integreat/cms#893]
**Is your feature request related to a problem? Please describe.**
The react-native app needs the `path` instead of the `id` in this response: [see here](https://github.com/Integreat/cms/wiki/REST-APIv3-Documentation#response-4)

**Describe the solution you'd like**
Return the `path` instead of the `id`.

**Describe alternatives you've considered**
There are none.

**Comment by svenseeberg** [comment]
As the API is currently already in use, we probably want backward compatibility. Keeping the ID does not require that much bandwidth. Therefore I vote for adding the path instead of replacing the ID.

**Comment by NKlug** [comment]
Btw, this is only relevant for the `deleted` array as far as I can see. I think the path is already being returned for the `changed` array. If not, it should also be added there.

**Comment by timoludwig** [comment]
There's a very fundamental problem with this: Once a page has been completely deleted in wordpress, also the path is deleted from the database and we cannot return it anymore. The only way to get around this is if you specify the path in your request already. It makes the diff-process a bit messy, but I think I can get the functionality working with using either ids or paths and return the deleted paths whenever it was specified in the request already.

**Comment by NKlug** [comment]
Sounds good to me. Would it be any messier than what we currently do with the ids? Checking if they are still in the DB and if not returning them as deleted?
It would be perfectly fine for us if we could `POST` the paths instead of the ids and get a diff of the paths.

**Comment by svenseeberg** [comment]
The problem is that paths are not permanent in the Wordpress database, only the ID does not change. AFAICT we cannot be sure that we can find the same page again with just the path.

**Comment by timoludwig** [comment]
As long as permalinks are not mapped to other existing pages, wordpress remembers the old permalinks and associates them with the original post. So each page has exactly one current path, but several paths can have the same page.
@NKlug Yes, it is messier than using ids internally, but it I think the effort is justifiable.
@svenseeberg But the path + hash combinations are still unique, so it is perfectly fine to use the path instead of ids. The only side-effect for the client is that it will assume a delete + insert instead of an update when a permalink changes.

**Comment by svenseeberg** [comment]
You're right.
